apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000     # The port the service is exposed on
      targetPort: 5000 #e port the backend container is running on
  type: ClusterIP  # Internal service (frontend will use this)
